### PR TITLE
Swap sed expression with tomlq

### PR DESCRIPTION
**Pull request by cbcoutinho**
Tomlq is a `toml` file parser built off of `jq`. It simplifies the sed
expression

### CODE REVIEW

**Comment by nicks** [comment]
Hi @cbcoutinho ! Thanks for the PR! I didn't know about `tomlq` until today.

But when I tested it, it didn't work for me.

I think you might be confused about what the sed script does? this edits the containerd config inside the minikube vm...your version tries to copy it out of the minikube vm. I don't think that will work.

**Comment by nicks** [comment]
Flipped a switch on circleci so that when circleci comes back online from their outage, it will run this script against the ci test (i hope :pray: )

**Comment by cbcoutinho** [comment]
I made some changes to the script so that it copies the tomlq output after minikube starts up, and also added tomlq to the circleci config.

I use the $MINIKUBE_HOME/files shortcut for other files, but it seems the containerd config is overwritten on startup, so didn't respect that file. Here's the PR that implemented it FYI https://github.com/kubernetes/minikube/pull/1917

**Comment by cbcoutinho** [comment]
@nicks I'm having trouble with the test in the CI runner with kubectl and the minikube test pod. Any ideas?

**Comment by nicks** [comment]
@cbcoutinho it might be worthwhile to step back a bit. can you talk a bit more about what problem you're solving?

I was open to replacing the sed script with tomlq if it made things simpler. But it looks like this is making things more complex.

For background: The reason that this sed script is so complex isn't because I like obfuscated sed scripts :grimacing: . It's because it's really hard to patch the container runtime in minikube in a portable way (a way that works across lots of different host machines and lots of different minikube configurations).

One of the things I really like about Kind is that it gives you a portable way to patch the container runtime with its `containerdConfigPatch` stuff (https://pkg.go.dev/sigs.k8s.io/kind@v0.11.0/pkg/apis/config/v1alpha4#Cluster), and maybe the better solution is to try to get something tomlq-like into minikube core.

thoughts?

**Comment by nicks** [comment]
Closing this as stale

**Pull request closed without merging**
